### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by samemon** [Nobelz/RateMyProfessorAPI#7]
The calls return None for valid examples. Any update?

**Comment by Nobelz** [comment]
At the moment, this API is not maintained on a regular basis. However, could you provide an example where it doesn't work?

**Comment by glenviewjeff** [comment]
The example you provided on the main project page isn't working. 

![image](https://user-images.githubusercontent.com/334914/200132382-7808762e-cccc-4516-97a4-80c015d6fc74.png)

**Comment by ChrisBryann** [comment]
It seems RateMyProfessors.com updated their website. 
This code:
`data = re.findall(r'/campusRatings\.jsp\?sid=(\d+)', page.text)` from __init__py on line 55 causes data to be None. This is because the website doesn't have any link that has those criteria.

**Comment by ChrisBryann** [comment]
I could try to work on fixing this if you are okay with it.

**Comment by glenviewjeff** [comment]
Please do! Thanks

**Comment by ChrisBryann** [comment]
@Nobelz Hi, I forked your repository and made fixes. I requested a pull request and please do a sanity check on it. Thanks.

**Comment by Nobelz** [comment]
v.1.3.3
